const extractBtn = document.getElementById("extract");
const exportBtn = document.getElementById("export");
const status = document.getElementById("status");
const formatSelect = document.getElementById("format");
const cookieList = document.getElementById("cookieList");
const selectedOnlyCheckbox = document.getElementById("selectedOnly");

let allCookies = [];

// Extract cookies
extractBtn.addEventListener("click", () => {
  status.textContent = "Extracting cookies...";
  exportBtn.disabled = true;
  cookieList.innerHTML = "";

  chrome.cookies.getAll({}, (cookies) => {
    if (chrome.runtime.lastError) {
      status.textContent = "Error reading cookies";
      console.error(chrome.runtime.lastError);
      return;
    }

    allCookies = cookies;
    status.textContent = "Loaded " + cookies.length + " cookies";
    exportBtn.disabled = cookies.length === 0;

    cookies.forEach((c, index) => {
      const row = document.createElement("div");
      row.className = "cookieRow";

      row.innerHTML = `
        <label>
          <input type="checkbox" data-index="${index}">
          <strong>${c.name}</strong><br>
          <small>${c.domain}</small>
        </label>
      `;

      cookieList.appendChild(row);
    });
  });
});

// Export cookies
exportBtn.addEventListener("click", () => {
  status.textContent = "Exporting cookies...";

  let cookiesToExport = allCookies;

  if (selectedOnlyCheckbox.checked) {
    const checked = cookieList.querySelectorAll("input[type=checkbox]:checked");
    cookiesToExport = Array.from(checked).map(cb => allCookies[cb.dataset.index]);
  }

  if (cookiesToExport.length === 0) {
    status.textContent = "No cookies selected";
    return;
  }

  const format = formatSelect.value;
  let data = "";
  let filename = "";

  // JSON
  if (format === "json") {
    data = JSON.stringify(cookiesToExport, null, 2);
    filename = "ferreluxade-cookies.json";
  }

  // Plain text
  if (format === "txt") {
    data = cookiesToExport.map(c =>
      "Name: " + c.name + "\n" +
      "Domain: " + c.domain + "\n" +
      "Value: " + c.value + "\n" +
      "---------------------\n"
    ).join("");

    filename = "ferreluxade-cookies.txt";
  }

  // Netscape format
  if (format === "netscape") {
    data = "# Netscape HTTP Cookie File\n";
    data += "# Generated by Ferreluxade\n\n";

    cookiesToExport.forEach(c => {
      if (!c.expirationDate) return;

      const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
      const includeSubdomains = "TRUE";
      const path = c.path || "/";
      const secure = c.secure ? "TRUE" : "FALSE";
      const expiration = Math.floor(c.expirationDate);

      data += [
        domain,
        includeSubdomains,
        path,
        secure,
        expiration,
        c.name,
        c.value
      ].join("\t") + "\n";
    });

    filename = "netscape.txt";
  }

  const blob = new Blob([data], { type: "text/plain" });
  const url = URL.createObjectURL(blob);

  chrome.downloads.download({
    url: url,
    filename: filename,
    saveAs: true
  }, () => {
    if (chrome.runtime.lastError) {
      status.textContent = "Download failed";
      console.error(chrome.runtime.lastError);
    } else {
      status.textContent = "Export complete";
    }
  });
});